{% set name = "sciluigi" %}
{% set version = "0.10.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "bfa16d1986bb405daf9032d63079e494f612461e5957f376b08d5bff21b09e9b" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - luigi

test:
  imports:
    - sciluigi

about:
  home: https://github.com/pharmbio/sciluigi
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Helper library for writing dynamic, flexible workflows in luigi
  dev_url: https://github.com/pharmbio/sciluigi
  doc_url: https://github.com/pharmbio/sciluigi

extra:
  recipe-maintainers:
    - pmlandwehr
