{% set name = "sciluigi" %}
{% set version = "0.9.6b7" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "201ba29b0260981955e94542dc66aa4321b14cff3132281209839e6c6486ff5a" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - luigi >=1.3,<=2.1

test:
  imports:
    - sciluigi

about:
  home: https://github.com/pharmbio/sciluigi
  # license_file: No MANIFEST.in - see https://github.com/pharmbio/sciluigi/pull/35
  # Manually including a copy.
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Helper library for writing dynamic, flexible workflows in luigi'
  dev_url: https://github.com/pharmbio/sciluigi
  doc_url: https://github.com/pharmbio/sciluigi

extra:
  recipe-maintainers:
    - pmlandwehr
