travis:
  secure:
    BINSTAR_TOKEN: cmedG90MW2pdz8q9qjVzF1huvX+afdKjSOG7/V0n81p0hduav2en1hI9ebZ/xe3eTjxlpB0GGQFX1mBa40fmZI7AwsSReUcp2kFiWBFw+Rqh/sB6SbIIFGbRnxKvAfYo95Nq7rfiuVUNUM+h6bizFt6ALwZ0kgzytZ7CWnfThzv4Z+OhbSqlfjQ+8Fc5UGnI7LU3VBt3oKdNGMMkFBJaj69Uw6Fe1pKV1Nn/py/1r4Ttafr8meXdVP3lQAWvwlmK3ea6uiG5wfKwKLzQwOAitJ+jx9AirMYps8s89s5Xsc0dt98LcI8gGiEYgVWwq3zMm/EIBsABKOBVnuRQSw1gKmicv6tWDkK61P4IOpytmKhT8S5DvE/iaecLGC3iMIqNJ7pYybmEKQmIzpHEo+pIdkYT8nS3AqP60r7CkSykH9MaSFIo317Meb9OgaK+kx53XDEnQFXKpNaejXV/6T6WEvbxYx8WAAeboHfzF/yMMp4PPuGaXfekPdF29PpmFtXUbDxho7ozediWxL1Cugd1MGXdT1VJyZtg96Qbe9x2Uat3321BfYfkmoRG69vTRUOg57q2whzzJr8N+qPgHlOkoGYeLoR8txvQRzHlONnXCU86sMQxrKSmO20h2Qkn3gw5YpCiLtFM0H04zdKWKgwtJQcwfQTD/MFcReOheZQJk34=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
