travis:
  secure:
    BINSTAR_TOKEN: WyyBM/S134Y29IDTTy7MBvnaKvADkZ0t1+CyZAnSi8tqz5zg1FJ4NCBWVKE36aZJvfpowwGfRpJPWlD+IiFnU+Rf5Bn482iInVjKTrVMSrDZfHtQt6zszSJQcEHKH6TSNjklESQHFugGAhYZrRgpFNuSm744mgJqo3QxAAbOMApnsG4cA6SzozH5zGFzfmaDWZRzfk1YA0bj22dq1AMoXFfNOB6RR6rudKwl+lGnVJB5Q1VyzROoqiBFl9pvsIN/3OmriB6T6tFrRfNRawVJuMkF+rvk6o8A6denp53auEWC6t+TEWCY1BkC3zJeSAkLZCtgjOLgtltA9snyeX7+g82LX/W0fZZveE40fHgW94hymb41NOBZC1kkB+Vf4IXYsCvHmINGOgrhEt3OMJ06LXscpQV0hQ7Nknmj9kKcwM6PVCb6djrB1OApvMdvisddHNJgdOqbEEkt/oFkH3lC2NZ+LjccFSM+gGahAq1gJvKOWQxxvnZF02zCAH1P4Y3IbbA0FV2n92NjpOMm66G3pGX5JAvk5uDtLoe9mNyg9tDDNJcXhUmA92MrHMIkNT22Mez1w9qDei8A8qt65xe9/swmc/Fx/wOBk0/UfPIEHNFESudPIKbMzbKo+68lovRA4Tml5XA6XRlbdEVPWbuY/7WX0xoJRV/X9sENhh7XnkI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
